### PR TITLE
update sshd-core from 1.7.0 to 2.2.0

### PR DESCRIPTION
**Pull request by based2**
https://mvnrepository.com/artifact/org.apache.sshd/sshd-core

https://mina.apache.org/sshd-project/

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
@based2 Just to make sure, are you a real human or an update bot?

**Comment by based2** [comment]
I am neither an ai, nor a bot, nor a golem, nor an automaton.
<°//><

**Comment by based2** [comment]
btw you can use one: https://help.github.com/en/articles/configuring-automated-security-fixes

**Comment by oleg-nenashev** [comment]
@based2 Although we appreciate all kinds of contribution, the particular changes you submit do not help, because...

* Changes are not tested on the local machine, many PRs just fail due to upper bounds dependencies and other issues which could have been easily discovered locally
* There is no changelog references, so a maintainer has to figure out update contents 
* There is no references to related Jenkins JIRA tickets where it is relevant, e.g. in this particular PR

I kindly ask to reconsider your approach, because it has already caused a lot of negative feedback from plugin maintainers

**Comment by based2** [comment]
ok, thanks

**Comment by oleg-nenashev** [comment]
We are exploring options like automated security fixes and Dependabot now. You can see them enabled in some repositories. So yes, I hope such minor dependency management tools will be automated soon across the org

**Pull request closed without merging**
