### PR TITLE
Update to the new Parent POM

### PR DESCRIPTION
**Pull request by oleg-nenashev**
- [x] - New parent POM
- [x] - Jenkins core dependency has been upgraded to 1.580.3
- [x] - maven-hpi-plugin has been upgraded to 1.119 (latest)
- [x] - Refactor the test
- [x] - Fix issues discovered by FindBugs, suppress DM_ENCODING

@reviewbybees @jenkinsci/code-reviewers @aheritier

### CODE REVIEW

**Comment by recena** [comment]
No PR builder for this repo?

**Comment by aheritier** [comment]
Jenkins core dependency has been upgraded to 1.580.3 => you reverted it ?

**Comment by oleg-nenashev** [comment]
@aheritier 
> Jenkins core dependency has been upgraded to 1.580.3 => you reverted it ?

Nope. It's 1.580.3 now. Actually we may want to go after Java 7 hence 1.625.x is also good in this case.

@recena 

> No PR builder for this repo?

Or it is dead... Works on my machine (c)

**Comment by aheritier** [comment]
no I think we have no build @recena 

@oleg-nenashev yes i misread your commit history. Yes we may go to 1.625 / java 7 I think

🐝

**Comment by oleg-nenashev** [comment]
Created a CI build

**Comment by oleg-nenashev** [comment]
@recena Well, setting up of CI was really reasonable here :D

**Comment by recena** [comment]
🐝 , thank you @oleg-nenashev

**Comment by oleg-nenashev** [comment]
@reviewbybees done

**Pull request merged**
